Board/urls.py
from django.urls import path
from Board import views

app_name='Board'
urlpatterns = [
    path('', views.BoardList.as_view(), name='list'),
    path('<int:pk>/', views.BoardDetail.as_view(), name='detail'),
    path('create_board/', views.BoardCreate.as_view(),name='board_create'),
    path('delete_board/<int:pk>/', views.BoardDelete,name='board_delete'),
    path('update_board/<int:pk>/', views.BoardUpdate.as_view(),name='board_update'),
]

bingo/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='bingo'
urlpatterns =[
    path('detail1/',views.Detail1,name='detail1'),
    path('detail2/',views.Detail2,name='detail2'),
    path('detail3/',views.Detail3,name='detail3'),
    path('',views.Bingo,name='bingo'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views 

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from bingo import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bingo/',include('bingo.urls')),
    path('Board/',include('Board.urls')),
    path('common/',include('common.urls')),
    path('',views.Bingo),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Board/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.
class Board(models.Model):
  title = models.CharField(max_length=30)
  content = models.TextField()
  file_upload = models.FileField(upload_to='board/data/%Y/%m/%d/', blank=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
    return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/Board/{self.pk}/'

bingo/models.py
from django.db import models

# Create your models here.

common/models.py
from django.db import models

# Create your models here.

Board/forms.py
from django import forms
from .models import Board
from django.utils.safestring import mark_safe

class CustomFileWidget(forms.FileInput):
  def __init__(self, attrs={}):
      super().__init__(attrs)

  def render(self, name, value, attrs=None, renderer=None):
    print(value, name)
    output = []
    if value and hasattr(value, "url"):
      file_name = value.url.split('/')[-1]
      output.append(super().render(name, value, attrs))
      output.append(f'<span class="form-control">첨부파일 : <a class="text-reset text-decoration-none" target="_blank" href="{value.url}">{file_name}</a><input class="form-check-input ms-2 me-1" type="checkbox" name="upload_clear" id="upload_clear_id" value="upload_del">Delete</span>')
      return mark_safe(u''.join(output))
    output.append(super().render(name, value, attrs))
    return mark_safe(u''.join(output))

class BoardUpdateForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['title'].widget.attrs.update({'class': 'form-control'})
    self.fields['file_upload'].widget.attrs.update({'class': 'form-control'})
    self.fields['content'].widget.attrs.update({'class': 'form-control', 'rows':'20'})
  
  
  class Meta:
    model = Board
    fields = ('title', 'file_upload', 'content')
    widgets = {
      'file_upload': CustomFileWidget,
    }


class BoardCreateForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['title'].widget.attrs.update({'class': 'form-control'})
    self.fields['file_upload'].widget.attrs.update({'class': 'form-control'})
    self.fields['content'].widget.attrs.update({'class': 'form-control', 'rows':'20'})
  
  class Meta:
    model = Board
    fields = ('title', 'file_upload', 'content')

common/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

Board/views.py
from django.shortcuts import get_object_or_404, render, redirect
from Board.models import Board
from Board.forms import BoardCreateForm, BoardUpdateForm
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from django.contrib.auth.decorators import login_required
from config import settings
import os

from django.core.exceptions import PermissionDenied
class BoardUpdate(UpdateView):
    model = Board
    form_class = BoardUpdateForm
    template_name = 'Board/board_form_update.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        if self.get_object().file_upload.name != '':
            if self.object.file_upload != self.get_object().file_upload.name:
                file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
                if os.path.exists(file_upload_path):
                    os.remove(file_upload_path)
            if 'upload_clear' in self.request.POST:
                file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
                if os.path.exists(file_upload_path):
                    os.remove(file_upload_path)
                    self.object.file_upload = ''
        return super().form_valid(form)


class BoardList(ListView):
    model = Board
    template_name = 'Board/board_list.html'
    ordering = '-pk'
    paginate_by = 10

class BoardDetail(DetailView):
    model = Board
    template_name = 'Board/board_detail.html'

class BoardCreate(CreateView):
    model = Board
    form_class = BoardCreateForm
    template_name = 'Board/board_form.html'
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super().form_valid(form)
        else:
            return redirect('/Board')

@login_required(login_url='common:login')
def BoardDelete(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.user != board.author:
        return redirect('Board:detail', pk=pk)
    if board.file_upload:
        file_upload_path = os.path.join(settings.MEDIA_ROOT, board.file_upload.path)
        if os.path.exists(file_upload_path):
            os.remove(file_upload_path)
    board.delete()
    return redirect('Board:list')

bingo/views.py
from django.shortcuts import render

# Create your views here.

def Detail1(request):
    return render(request,'bingo/detail1.html')

def Detail2(request):
    return render(request,'bingo/detail2.html')

def Detail3(request):
    return render(request,'bingo/detail3.html')

def Bingo(request):
    return render(request,'bingo/bingo.html')

common/views.py
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib.auth import authenticate, login

# Create your views here.
def signup(request):
  if request.method == "POST":
    form = UserForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      raw_password = form.cleaned_data.get('password1')
      user = authenticate(username=username, password=raw_password)
      login(request, user) 
      return redirect('/')
  else:
      form = UserForm()
  return render(request, 'common/signup.html', {'form': form})

templates/bingo/bingo.html
{% extends "bingo_base.html" %}
{% load static %}
{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"                        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"                              integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
<!-- Bootstrap CDN URL -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"                        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"                              integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CDN URL -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"                        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"                              integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <!-- Jquery CDN URL -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>

  <!-- Fontawesome URL -->
  <script src="https://kit.fontawesome.com/53e4af2e34.js" crossorigin="anonymous"></script>


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"                        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"                              integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
  <title>Django WEB</title>
{% endblock %}

{% block content %}




   

    <section data-bs-version="5.1" class="slider1 cid-tq6hOOt26E" id="slider1-17">
    
        <div class="carousel slide" id="tq6ZeJwBdU" data-ride="carousel" data-bs-ride="carousel" data-interval="4000" data-bs-interval="4000">
            <ol class="carousel-indicators">
                <li data-slide-to="0" data-bs-slide-to="0" class="active" data-target="#tq6ZeJwBdU" data-bs-target="#tq6ZeJwBdU"></li>
                <li data-slide-to="1" data-bs-slide-to="1" data-target="#tq6ZeJwBdU" data-bs-target="#tq6ZeJwBdU"></li>
                <li data-slide-to="2" data-bs-slide-to="2" data-target="#tq6ZeJwBdU" data-bs-target="#tq6ZeJwBdU"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item slider-image item active">
                    <div class="item-wrapper">
                        <img class="d-block w-100" src="{%static "assets/images/4-2-1280x720.jpg"%}" alt="" height="full" width="full">
                        
                        <div class="carousel-caption">
                            <h5 class="mbr-section-subtitle mbr-fonts-style display-5">
                                <strong>Splatoon 3</strong></h5>
                            <p class="mbr-section-text mbr-fonts-style display-7">대자연에서, 대도시에서, 더욱 더 넓어지는 영역 배틀!</p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item slider-image item">
                    <div class="item-wrapper">
                        <img class="d-block w-100" src="{%static "assets/images/사진.jpg"%}" alt="">
                        
                        <div class="carousel-caption">
                            <h5 class="mbr-section-subtitle mbr-fonts-style display-5"><strong>Evil Hunter Tycoon</strong></h5>
                            <p class="mbr-section-text mbr-fonts-style display-7">흥미진진한 전투 컨텐츠 !! 최강의 헌터를 가리는 PVP</p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item slider-image item">
                    <div class="item-wrapper">
                        <img class="d-block w-100" src="{%static "assets/images/-449x294.jpeg"%}" alt="">
                        
                        <div class="carousel-caption">
                            <h5 class="mbr-section-subtitle mbr-fonts-style display-5"><strong>SUDDEN ATTACK</strong></h5>
                            <p class="mbr-section-text mbr-fonts-style display-7">전쟁 여론이 커지게 되자, 강대국에서는 치안 유지를 위한 경찰 부대를<br>가장한 특수부대(블루팀)을 보내 반군과 잔호크의 부대를 소탕하려 하는데...</p>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control carousel-control-prev" role="button" data-slide="prev" data-bs-slide="prev" href="#tq6ZeJwBdU">
                <span class="mobi-mbri mobi-mbri-arrow-prev" aria-hidden="true"></span>
                <span class="sr-only visually-hidden">Previous</span>
            </a>
            <a class="carousel-control carousel-control-next" role="button" data-slide="next" data-bs-slide="next" href="#tq6ZeJwBdU">
                <span class="mobi-mbri mobi-mbri-arrow-next" aria-hidden="true"></span>
                <span class="sr-only visually-hidden">Next</span>
            </a>
        </div>
    </section>


    {% include "timer.html" %}
    <br><br><br>
    <div style="text-align:center">
        <h2><strong>ALL GAEMS </strong></h2>
    </div>
    <span class="placeholder col-12 bg-dark"></span>
    <br><br>
    <div class="container" style="margin: auto;">
        <div class="row">
            <div class="col-lg-8">
                <div class="card-body" >
                    <img src="{%static "bingo/bingo/images/splatoon.gif"%}"  height="100%" width="100%">
                    
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card-body">
                    <h2 style="font-family: 'Fredoka One', cursive;">Splatoon 3</h2><hr>
                    <h3 style="font-family: 'Black Han Sans', sans-serif; font-size:xx-large;">대자연에서,<br> 대도시에서,<br>
                        더욱 더 넓어지는 <br>영역 배틀!</h3><hr>
                    <a href="{% url 'bingo:detail1' %}"><p style="font-family: 'Fredoka One', cursive;"><button type="button" class="btn btn-outline-dark">GO TO SPLATOON</button></p></a>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-lg-4">
                <div class="card-body" style="font-family: 'Fredoka One', cursive;">
                    <h2 style="font-family: 'Fredoka One', cursive;">Evil Hunter</h2><hr>
                    <h3 style="font-family: 'Black Han Sans', sans-serif; font-size:xx-large;">흥미진진한 전투 컨텐츠 !!
                        최강의 헌터를 가리는 PVP</h3><hr>
                            <a href="{% url 'bingo:detail2' %}"><p style="font-family: 'Fredoka One', cursive;"><button type="button" class="btn btn-outline-dark">GO TO EVIL HUNTER </button></p></a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card-body" >
                    <img src="{%static "bingo/bingo/images/hunter.jpg"%}" height="100%" width="100%">
                    
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-lg-8">
                <div class="card-body" >
                    <img src="{%static "bingo/bingo/images/attack.jpg"%}"  height="100%" width="100%">
                    
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card-body">
                    <h2 style="font-family: 'Fredoka One', cursive;">Sudden Attack</h2><hr>
                    <h3 style="font-family: 'Black Han Sans', sans-serif; font-size:xx-large;">다양한 맵!<br>개인전, 팀 데스매치 등<br>다양한 모드 FPS!</h3><hr>
                    <a href="{% url 'bingo:detail3' %}"><p style="font-family: 'Fredoka One', cursive;"><button type="button" class="btn btn-outline-dark">GO TO SUDDEN ATTACK</button></p></a>
                </div>
            </div>
        </div>

    </div>
    <br><br>    <br><br>
    


    
{% endblock %}



templates/bingo_navbar.html
{% load static %}
<head>
  <meta charset="UTF-8">
  


  
  <!-- Bootstrap CDN URL -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"                        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"                              integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
</head>
<body>
<section data-bs-version="5.1" class="menu cid-tq6HRmehEl" once="menu" id="menu1-1q">
    
  <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
      <div class="container-fluid">
          <div class="navbar-brand">
              <span class="navbar-logo">
                  
                      <a href="{% url 'bingo:bingo' %}"><img src="{%static "assets/images/logo-100x100.png"%}" alt="" style="height: 3.8rem;"></a>
                  
              </span>
              <span class="navbar-caption-wrap"><a class="navbar-caption text-black text-primary display-5" href="{% url 'bingo:bingo' %}">DINGO BING</a></span>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <div class="hamburger">
                  <span></span>
                  <span></span>
                  <span></span>
                  <span></span>
              </div>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                <li class="nav-item dropdown">
                  <a class="nav-link link text-black text-primary dropdown-toggle " href="#" target="_blank" data-toggle="dropdown-submenu" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false" style="font-size: 16px;">PC</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown-875">
                    <a class="text-black text-primary dropdown-item " href="{% url 'bingo:detail3' %}">Sudden Attack</a>
                    <a class="text-black text-primary dropdown-item " href="#">Open예정</a>
                    
                      
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link link text-black text-primary dropdown-toggle " href="#" target="_blank" data-toggle="dropdown-submenu" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false" style="font-size: 16px;">Nintendo</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown-875">
                    <a class="text-black text-primary dropdown-item " href="{% url 'bingo:detail1' %}">Splatoon3</a>
                    <a class="text-black text-primary dropdown-item " href="#">Open예정</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link link text-black text-primary dropdown-toggle " href="{% url 'bingo:detail2' %}" target="_blank" data-toggle="dropdown-submenu" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false" style="font-size: 16px;">Mobile</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown-215">
                    <a class="text-black text-primary show dropdown-item " href="{% url 'bingo:detail2' %}">Evil Hunter</a>
                    <a class="text-black text-primary show dropdown-item " href="#">Open예정</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link link text-black text-primary dropdown-toggle " href="#" target="_blank" data-toggle="dropdown-submenu" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false" style="font-size: 16px;">Community</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown-992">
                    <a class="text-black text-primary show dropdown-item " href="#">TEAM</a>
                    <a class="text-black text-primary show dropdown-item " href="#">CONTACTS</a>
                    <a class="text-black text-primary show dropdown-item " href="#">FAQ</a>
                  </div>
                </li>
                <li class="nav-item">
                  <a class="nav-link link text-black text-primary show " href="{% url 'Board:list' %}" style="font-size: 16px;">게시판</a>
                </li>
                {% if user.is_anonymous %}
                <li class="nav-item">
                  <a class="nav-link link text-black text-primary show " href="{% url 'common:login' %}" style="font-size: 16px;">로그인</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link link text-black text-primary show " href="{% url 'common:signup' %}" style="font-size: 16px;">회원가입</a>
                </li>
                {% else %} 
                <li class="nav-item">
                  <a class="nav-link link text-black text-primary show " href="{% url 'Board:board_create' %}" style="font-size: 16px;">게시판작성</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link link text-black text-primary show " href="{% url 'common:logout' %}" style="font-size: 16px;" >로그아웃 [ {{user.username}} ]</a>
                </li>
                {% endif %}
                
              </ul>
              
              
          </div>
          
      </div>
  </nav>
</section>

</body>

templates/form_errors.html
{% if form.errors %}
<!-- Field Input Error -->
{% for field in form %}
  {% for error in field.errors %}
    <div class="alert alert-danger">
      <strong>{{ field.label }} </strong>{{ error }}
    </div>
  {% endfor %}
{% endfor %}

<!-- Non Field Error -->
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    <strong>{{ error }}</strong>
  </div>
{% endfor %} 
{% endif %}